# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_oauth1able}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["SAWADA Tadashi"]
  s.date = %q{2010-10-04}
  s.description = %q{OAuth1.x plugin for Devise}
  s.email = %q{cesare@mayverse.jp}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/devise/oauth1_controller.rb",
     "devise_oauth1able.gemspec",
     "lib/devise_oauth1able.rb",
     "lib/devise_oauth1able/config.rb",
     "lib/devise_oauth1able/controllers/url_helpers.rb",
     "lib/devise_oauth1able/internal_helpers.rb",
     "lib/devise_oauth1able/model.rb",
     "lib/devise_oauth1able/rails.rb",
     "lib/devise_oauth1able/routes.rb"
  ]
  s.homepage = %q{http://github.com/cesare/devise_oauth1able}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{OAuth1.x plugin for Devise}
  s.test_files = [
    "spec/devise_oauth1able_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, ["~> 0.4.2"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<oauth>, ["~> 0.4.2"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<oauth>, ["~> 0.4.2"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

